<?php

/**
 * Transaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    betyolo
 * @subpackage model
 * @author     Nguyen Anh Tuan
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Transaction extends BaseTransaction
{
  #type
  const DEPOSIT  = 1;
  const WITHDRAW = 2;

  static public $amounts = array(
    10000 => 10000,
    20000 => 20000,
    50000 => 50000,
    100000 => 100000,
    200000 => 200000,
    300000 => 300000,
    400000 => 400000,
    500000 => 500000,
  );

  public function deposit($hcoin = 0)
  {
    if ($this->getStatus() != 1 || $hcoin <= 0 ) {
      return false;
    }

    $user_hcoin = $this->getUser()->getProfile()->getHcoin();

    if (!$user_hcoin) {
      $user_profile = new UserProfile();
      $user_profile->setsfGuardUserId($this->getUser()->getId());
      $user_profile->setHcoin($hcoin);
    } else {
      $user_profile = Doctrine_Core::getTable('UserProfile')->find($this->getUser()->getId());
      $user_profile->setHcoin($user_hcoin + $hcoin);
    }
    $user_profile->save();

    $this->setStatus(2);
    $this->save();

    return true;
  }

  public function cancelDeposit()
  {
    $this->setStatus(3);
    $this->save();
  }
}
