BetyoloCategory:
    actAs: { Timestampable: ~ }
    columns:
        name: { type: string(255), notnull: true, unique: true }
        description:  { type: string(4000), notnull: true }


BetyoloSide:
    actAs: { Timestampable: ~ }
    columns:
        name: { type: string(255), notnull: true, unique: true }
        description:  { type: string(4000), notnull: true }
        category_id:  { type: integer, notnull: true }
    relations: 
        BetyoloCategory: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: BetyoloSide }


BetyoloBet:
    actAs: { Timestampable: ~ }
    columns:
        creator_id: { type: integer }
        description:  { type: string(4000), notnull: true }
        side_a_id: { type: integer, notnull: true }
        side_b_id: { type: integer, notnull: true }
        category_id:  { type: integer, notnull: true }
        status:  { type: integer }
        result:  { type: integer }
    relations:
        BetyoloCategory: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: BetyoloBet }
        BetyoloSide: { onDelete: CASCADE, local: side_a_id, foreign: id, foreignAlias: BetyoloSideA }
        BetyoloSide: { onDelete: CASCADE, local: side_b_id, foreign: id, foreignAlias: BetyoloSideB }
